// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class HealthCareAppTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Dispose();
  }
  [Test]
  public void tC1VerifyFooter() {
    driver.Navigate().GoToUrl("https://katalon-demo-cura.herokuapp.com/");
    Assert.That(driver.FindElement(By.XPath("//h4//strong")).Text, Is.EqualTo("CURA Healthcare Service"));
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-lg-10 col-lg-offset-1 text-center\"]//p[not (contains(@class, \"text-muted\"))]")).Text, Is.EqualTo("Atlanta 550 Pharr Road NE Suite 525\r\nAtlanta, GA 30305"));
    Assert.That(driver.FindElement(By.XPath("//i[@class=\"fa fa-phone fa-fw\"]/parent::li")).Text, Is.EqualTo("(678) 813-1KMS"));
    Assert.That(driver.FindElement(By.XPath("//i[@class=\"fa fa-envelope-o fa-fw\"]/following-sibling::a")).Text, Is.EqualTo("info@katalon.com"));
    var elements = driver.FindElements(By.XPath("//i[@class=\"fa fa-facebook fa-fw fa-3x\"]"));
        Assert.True(elements.Count > 0);
        _ = driver.FindElements(By.XPath("//i[@class=\"fa fa-twitter fa-fw fa-3x\"]"));
        Assert.True(elements.Count > 0);
        _ = driver.FindElements(By.XPath("//i[@class=\"fa fa-dribbble fa-fw fa-3x\"]"));
        Assert.True(elements.Count > 0);
    driver.Close();
  }
  [Test]
  public void tC2LoginandLogout() {
    driver.Navigate().GoToUrl("https://katalon-demo-cura.herokuapp.com/");
    var elements = driver.FindElements(By.XPath("//a[@id=\"btn-make-appointment\"]"));
    Assert.True(elements.Count > 0);
    Assert.That(driver.FindElement(By.XPath("//a[@id=\"btn-make-appointment\"]")).Text, Is.EqualTo("Make Appointment"));
    driver.FindElement(By.XPath("//a[@id=\"btn-make-appointment\"]")).Click();
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-sm-12 text-center\"]//h2")).Text, Is.EqualTo("Login"));
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-sm-12 text-center\"]//p[@class=\"lead\"]")).Text, Is.EqualTo("Please login to make appointment."));
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"form-group\"]//label[@for=\"txt-username\"]")).Text, Is.EqualTo("Username"));
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"form-group\"]//label[@for=\"txt-password\"]")).Text, Is.EqualTo("Password"));
    driver.FindElement(By.XPath("//input[@id=\"txt-username\"]")).SendKeys("John Doe");
    driver.FindElement(By.XPath("//input[@id=\"txt-password\"]")).SendKeys("ThisIsNotAPassword");
    driver.FindElement(By.XPath("//button[@id=\"btn-login\"]")).Click();
    driver.Navigate().GoToUrl("https://katalon-demo-cura.herokuapp.com/#appointment");
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-sm-12 text-center\"]//h2")).Text, Is.EqualTo("Make Appointment"));
    driver.FindElement(By.XPath("//a[@id=\"menu-toggle\"]")).Click();
    driver.FindElement(By.XPath("//a[@href=\"authenticate.php?logout\"]")).Click();
        _ = driver.FindElements(By.XPath("//a[@id=\"btn-make-appointment\"]"));
        Assert.True(elements.Count > 0);
    driver.Close();
  }
  [Test]
  public void tC3MakeanAppointment() {
    driver.Navigate().GoToUrl("https://katalon-demo-cura.herokuapp.com/");
    var elements = driver.FindElements(By.XPath("//a[@id=\"btn-make-appointment\"]"));
    Assert.True(elements.Count > 0);
    Assert.That(driver.FindElement(By.XPath("//a[@id=\"btn-make-appointment\"]")).Text, Is.EqualTo("Make Appointment"));
    driver.FindElement(By.XPath("//a[@id=\"btn-make-appointment\"]")).Click();
    driver.FindElement(By.XPath("//input[@id=\"txt-username\"]")).SendKeys("John Doe");
    driver.FindElement(By.XPath("//input[@id=\"txt-password\"]")).SendKeys("ThisIsNotAPassword");
    driver.FindElement(By.XPath("//button[@id=\"btn-login\"]")).Click();
    driver.Navigate().GoToUrl("https://katalon-demo-cura.herokuapp.com/#appointment");
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-sm-12 text-center\"]//h2")).Text, Is.EqualTo("Make Appointment"));
    {
      var dropdown = driver.FindElement(By.XPath("//div[@class=\"col-sm-4\"]//select[@id=\"combo_facility\"]"));
      dropdown.FindElement(By.XPath("//option[. = 'Hongkong CURA Healthcare Center']")).Click();
    }
    driver.FindElement(By.XPath("//input[@id=\"radio_program_none\"]")).Click();
    driver.FindElement(By.XPath("//input[@id=\"txt_visit_date\"]")).SendKeys("10/02/2025");
    driver.FindElement(By.XPath("//textarea[@id=\"txt_comment\"]")).SendKeys("Test");
    driver.FindElement(By.XPath("//button[@id=\"btn-book-appointment\"]")).Click();
    driver.Navigate().GoToUrl("https://katalon-demo-cura.herokuapp.com/appointment.php#summary");
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-xs-12 text-center\"]//h2")).Text, Is.EqualTo("Appointment Confirmation"));
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-xs-8\"]//p[@id=\"facility\"]")).Text, Is.EqualTo("Hongkong CURA Healthcare Center"));
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-xs-8\"]//p[@id=\"hospital_readmission\"]")).Text, Is.EqualTo("No"));
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-xs-8\"]//p[@id=\"program\"]")).Text, Is.EqualTo("None"));
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-xs-8\"]//p[@id=\"visit_date\"]")).Text, Is.EqualTo("10/02/2025"));
    Assert.That(driver.FindElement(By.XPath("//div[@class=\"col-xs-8\"]//p[@id=\"comment\"]")).Text, Is.EqualTo("Test"));
    driver.FindElement(By.XPath("//div[@class=\"col-xs-12\"]//p[@class=\"text-center\"]//a[@class=\"btn btn-default\"]")).Click();
    driver.Navigate().GoToUrl("https://katalon-demo-cura.herokuapp.com/");
        _ = driver.FindElements(By.XPath("//a[@id=\"menu-toggle\"]"));
        Assert.True(elements.Count > 0);
    driver.FindElement(By.XPath("//a[@id=\"menu-toggle\"]//i[@class=\"fa fa-bars\"]")).Click();
    driver.FindElement(By.XPath("//a[@href=\"authenticate.php?logout\"]")).Click();
    driver.Close();
  }
}
