// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC_1_Selenium Dev', async function() {
    await driver.get("https://www.selenium.dev/")
    await driver.manage().window().setRect({ width: 829, height: 602 })
    await driver.findElement(By.css(".navbar-toggler-icon")).click()
    await driver.findElement(By.linkText("Documentation")).click()
    await driver.findElement(By.css(".breadcrumb-item:nth-child(1) > a")).click()
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["root"])
    await driver.close()
  })
  it('TC_2_SoftUni', async function() {
    await driver.get("https://softuni.bg/")
    await driver.manage().window().setRect({ width: 1200, height: 672 })
    await driver.findElement(By.css(".desktop-logo")).click()
    await driver.close()
  })
  it('TC_3_Katalon Cura', async function() {
    await driver.get("https://katalon-demo-cura.herokuapp.com/")
    await driver.manage().window().setRect({ width: 1200, height: 672 })
    await driver.findElement(By.css(".fa-bars")).click()
    assert(await driver.findElement(By.xpath("//div[@class=\"text-vertical-center\"]//h1")).getText() == "CURA Healthcare Service")
    await driver.findElement(By.linkText("Login")).click()
    assert(await driver.findElement(By.xpath("//h2")).getText() == "Login")
    await driver.findElement(By.id("txt-username")).click()
    await driver.findElement(By.id("txt-username")).sendKeys("randomuser123")
    await driver.findElement(By.id("txt-password")).click()
    await driver.findElement(By.id("txt-password")).sendKeys("123456")
    await driver.findElement(By.id("btn-login")).click()
    assert(await driver.findElement(By.xpath("//p[@class=\"lead text-danger\"]")).getText() == "Login failed! Please ensure the username and password are valid.")
    await driver.close()
  })
  it('TC_6_Katalon Cura Loop', async function() {
    await driver.get("https://katalon-demo-cura.herokuapp.com/")
    await driver.findElement(By.css(".fa-bars")).click()
    await driver.findElement(By.linkText("Login")).click()
    const times = 3
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.id("txt-username")).sendKeys("desito07")
      await driver.findElement(By.id("txt-password")).sendKeys("123456")
      await driver.findElement(By.id("btn-login")).click()
    }
    await driver.close()
  })
  it('TC_4_Katalon Cura Header', async function() {
    await driver.get("https://katalon-demo-cura.herokuapp.com/")
    assert(await driver.findElement(By.xpath("//h1")).getText() == "CURA Healthcare Service")
    console.log(vars["heading"])
    vars["webpageTitle"] = await driver.getTitle()
    console.log(vars["pageTitle"])
    await driver.close()
  })
  it('TC_5_Katalon Cura If Else', async function() {
    await driver.get("https://katalon-demo-cura.herokuapp.com/")
    assert(await driver.findElement(By.xpath("//h1")).getText() == "CURA Healthcare Service")
    console.log(vars["heading"])
    vars["webpageTitle"] = await driver.getTitle()
    console.log(vars["pageTitle"])
    if (!!await driver.executeScript("return (arguments[0]===\"CURA Healthcare Service\")", vars["webpageTitle"])) {
      console.log("Matched")
    } else {
      console.log("Unmatched")
    }
    await driver.close()
  })
  it('TC_7_Katalon Cura Do Loop', async function() {
    await driver.get("https://katalon-demo-cura.herokuapp.com/")
    await driver.findElement(By.css(".fa-bars")).click()
    vars["check"] = await driver.executeScript("return 0")
    do {
      vars["check"] = await driver.executeScript("return arguments[0] + 1", vars["check"])
    } while(!!await driver.executeScript("return (arguments[0]<3)", vars["check"]))
    await driver.close()
  })
  it('TC_8_Katalon Cura While Loop', async function() {
    await driver.get("https://katalon-demo-cura.herokuapp.com/")
    await driver.findElement(By.css(".fa-bars")).click()
    vars["x"] = await driver.executeScript("return 0")
    while(!!await driver.executeScript("return (arguments[0]<3)", vars["x"])) {
      vars["x"] = await driver.executeScript("return arguments[0] + 1", vars["x"])
    }
  })
  it('TC_9_Katalon Cura ForEach Loop', async function() {
    await driver.get("https://katalon-demo-cura.herokuapp.com/")
    vars["x"] = await driver.executeScript("return [\"Audi\", \"Volvo\", \"BMW\", \"Opel\", \"Ford\"]")
    const collection = vars["x"]
    for (let i = 0; i < collection.length - 1; i++) {
      vars["itr"] = vars["x"][i]
      console.log(vars["itr"])
    }
  })
})
