// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC2AdditemtotheshoppingcartusingDoLoopTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC2AdditemtotheshoppingcartusingDoLoop() {
    driver.Navigate().GoToUrl("https://www.saucedemo.com");
    driver.FindElement(By.XPath("//input[@id=\"user-name\"]")).SendKeys("standard_user");
    driver.FindElement(By.XPath("//input[@id=\"password\"]")).SendKeys("secret_sauce");
    driver.FindElement(By.XPath("//input[@id=\"login-button\"]")).Click();
    driver.Navigate().GoToUrl("https://www.saucedemo.com/inventory.html");
    Assert.That(driver.FindElement(By.XPath("//span[@class=\"title\"]")).Text, Is.EqualTo("Products"));
    vars["times"] = js.ExecuteScript("return 1");
    do {
      driver.FindElement(By.XPath("(//button[@class=\"btn btn_primary btn_small btn_inventory \"])[last()]")).Click();
      vars["times"] = js.ExecuteScript("return arguments[0] + 1", vars["times"]);
    } while ((Boolean) js.ExecuteScript("return (arguments[0] <= 6)", vars["times"]));
    driver.Close();
  }
}
