// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC3RemoveitemtotheshoppingcartusingTimesTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC3RemoveitemtotheshoppingcartusingTimes() {
    driver.Navigate().GoToUrl("https://www.saucedemo.com");
    driver.FindElement(By.XPath("//input[@id=\"user-name\"]")).SendKeys("standard_user");
    driver.FindElement(By.XPath("//input[@id=\"password\"]")).SendKeys("secret_sauce");
    driver.FindElement(By.XPath("//input[@id=\"login-button\"]")).Click();
    driver.Navigate().GoToUrl("https://www.saucedemo.com/inventory.html");
    Assert.That(driver.FindElement(By.XPath("//span[@class=\"title\"]")).Text, Is.EqualTo("Products"));
    vars["times"] = js.ExecuteScript("return 6");
    var times = 6;
    for(int i = 0; i < times; i++) {
      driver.FindElement(By.XPath("(//button[@class=\"btn btn_secondary btn_small btn_inventory \"])[last()]")).Click();
    }
  }
}
